spring.profiles.active=dev
spring.data.rest.base-path=/api
spring.datasource.platform=postgres
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
#server.port=${PORT:8080}
#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.security.oauth2.client.registration.auth0.client-id=${AUTH0_CLIENT_ID}
#spring.security.oauth2.client.registration.auth0.client-secret=${AUTH0_CLIENT_SECRET}
#spring.security.oauth2.client.provider.auth0.issuer-uri=${AUTH0_ISSUER_URI}
#cloudinary.url=${CLOUDINARY_URL}