server.port=${PORT:8080}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.security.oauth2.client.registration.auth0.client-id=${AUTH0_CLIENT_ID}
spring.security.oauth2.client.registration.auth0.client-secret=${AUTH0_CLIENT_SECRET}
spring.security.oauth2.client.provider.auth0.issuer-uri=${AUTH0_ISSUER_URI}
cloudinary.url=${CLOUDINARY_URL}
okta.oauth2.issuer=${AUTH0_ISSUER_URI}
okta.oauth2.client-id=${AUTH0_CLIENT_ID}
okta.oauth2.client-secret=${AUTH0_CLIENT_SECRET}